import JSZip from 'jszip';

/**
 * Downloads a single file from string content or a Blob
 */
export const downloadFile = (content, filename) => {
  const blob = content instanceof Blob ? content : new Blob([content], { type: 'text/plain;charset=utf-8' });
  
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Generates and downloads a ZIP file containing the code and a README
 */
export const downloadZip = async (code, language, title = 'project') => {
  const zip = new JSZip();
  
  const extMap = {
    javascript: 'js',
    typescript: 'ts',
    python: 'py',
    java: 'java',
    cpp: 'cpp',
    go: 'go',
    php: 'php',
    rust: 'rs',
    sql: 'sql'
  };

  const ext = extMap[language] || 'txt';
  const filename = `main.${ext}`;

  // Add the source code file
  zip.file(`src/${filename}`, code);
  
  // Add a basic README
  zip.file('README.md', `# ${title}\n\nGenerated by AI Code Generator.\n\n## Language\n${language}`);

  try {
    const blob = await zip.generateAsync({ type: 'blob' });
    downloadFile(blob, `${title.replace(/\s+/g, '_')}_source.zip`);
  } catch (error) {
    console.error("Error generating ZIP:", error);
    throw error;
  }
};
